# Generated by Django 4.1.3 on 2022-11-21 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('certification', models.CharField(choices=[('EMT-B', 'EMT-B'), ('EMT-P', 'EMT-P'), ('LPN', 'LPN'), ('RN', 'RN')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('PT', 'PT'), ('PT-S', 'PT-S'), ('FT-S', 'FT-S')], max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 11, 21, 2, 34, 30, 240767), null=True)),
                ('nature', models.CharField(choices=[('A', 'A - ALLERGIC REACTION'), ('B', 'B - BITE/STING'), ('C', 'C - CARDIAC'), ('E', 'E - EXPOSURE'), ('F', 'F - FAINT'), ('G', 'G - GUEST ASSISTANCE'), ('H', 'H - HEAT RELATED'), ('I', 'I - ILLNESS'), ('R', 'R - RESPIRATORY'), ('T', 'T - TRAUMA'), ('U', 'U - UNKNOWN'), ('X', 'X - SEIZURE')], max_length=100, null=True)),
                ('red', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('caller', models.CharField(default='SECURITY', max_length=100, null=True)),
                ('on_scene_time', models.TimeField(blank=True, default=None, null=True)),
                ('upgrade_time', models.TimeField(blank=True, default=None, null=True)),
                ('ems_on_scene_time', models.TimeField(blank=True, default=None, null=True)),
                ('ems_clear_scene_time', models.TimeField(blank=True, default=None, null=True)),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.responder')),
            ],
        ),
    ]
