# Generated by Django 4.1.3 on 2022-11-21 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 2, 35, 40, 422282), null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(choices=[('Culinary', 'Culinary'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Games', 'Games'), ('Grounds', 'Grounds'), ('Guest Relations', 'Guest Relations'), ('HR', 'HR'), ('Maintenance', 'Maintenance'), ('Merchandise', 'Merchandise'), ('Security', 'Security'), ('Traffic', 'Traffic'), ('Zoo', 'Zoo')], max_length=100, null=True)),
                ('reason', models.CharField(max_length=250, null=True)),
                ('notes', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='call',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 2, 35, 40, 422099), null=True),
        ),
    ]
