# Generated by Django 4.1.3 on 2022-11-21 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_walkin_alter_call_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 2, 43, 57, 701874), null=True),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 2, 43, 57, 702047), null=True),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
