# Generated by Django 4.1.3 on 2022-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_call_datetime_alter_walkin_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responder',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='responder',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
