# Generated by Django 4.1.3 on 2022-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_rename_name_responder_firstname_responder_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
