# Generated by Django 4.1.3 on 2022-11-22 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_responder_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkin',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 17, 47, 7, 309560), null=True),
        ),
    ]
