# Generated by Django 4.1.3 on 2022-11-22 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_alter_walkin_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 17, 48, 43, 851364), null=True),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 17, 48, 43, 851894), null=True),
        ),
    ]
