# Generated by Django 4.1.3 on 2022-11-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_call_cancel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='zone',
            field=models.CharField(blank=True, choices=[('701', '701'), ('705', '705'), ('710', '710'), ('720', '720'), ('730', '730'), ('740', '740'), ('745', '745')], max_length=100, null=True),
        ),
    ]
