# Generated by Django 4.1.3 on 2022-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_alter_call_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='license_scan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
