# Generated by Django 4.1.3 on 2022-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0018_responder_license_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='cpr_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responder',
            name='cpr_scan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
