# Generated by Django 4.1.3 on 2022-12-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0019_responder_cpr_expiration_responder_cpr_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='zone',
            field=models.CharField(choices=[('701', '701'), ('705', '705'), ('710', '710'), ('720', '720'), ('725', '725'), ('730', '730'), ('740', '740'), ('745', '745')], default='701', max_length=100, null=True),
        ),
    ]
