# Generated by Django 4.1.3 on 2022-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0021_responder_license_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('emp_id', models.CharField(max_length=10, null=True)),
                ('dob', models.DateTimeField(null=True)),
            ],
        ),
    ]
