# Generated by Django 4.1.3 on 2022-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0024_minor_consent_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_1', models.TimeField(blank=True, null=True)),
                ('t_2', models.TimeField(blank=True, null=True)),
                ('t_3', models.TimeField(blank=True, null=True)),
                ('t_4', models.TimeField(blank=True, null=True)),
                ('t_5', models.TimeField(blank=True, null=True)),
                ('t_6', models.TimeField(blank=True, null=True)),
                ('p5_1', models.CharField(blank=True, max_length=100, null=True)),
                ('p5_2', models.CharField(blank=True, max_length=100, null=True)),
                ('p5_3', models.CharField(blank=True, max_length=100, null=True)),
                ('p5_4', models.CharField(blank=True, max_length=100, null=True)),
                ('p5_5', models.CharField(blank=True, max_length=100, null=True)),
                ('p5_6', models.CharField(blank=True, max_length=100, null=True)),
                ('p10_1', models.CharField(blank=True, max_length=100, null=True)),
                ('p10_2', models.CharField(blank=True, max_length=100, null=True)),
                ('p10_3', models.CharField(blank=True, max_length=100, null=True)),
                ('p10_4', models.CharField(blank=True, max_length=100, null=True)),
                ('p10_5', models.CharField(blank=True, max_length=100, null=True)),
                ('p10_6', models.CharField(blank=True, max_length=100, null=True)),
                ('p20_1', models.CharField(blank=True, max_length=100, null=True)),
                ('p20_2', models.CharField(blank=True, max_length=100, null=True)),
                ('p20_3', models.CharField(blank=True, max_length=100, null=True)),
                ('p20_4', models.CharField(blank=True, max_length=100, null=True)),
                ('p20_5', models.CharField(blank=True, max_length=100, null=True)),
                ('p20_6', models.CharField(blank=True, max_length=100, null=True)),
                ('p30_1', models.CharField(blank=True, max_length=100, null=True)),
                ('p30_2', models.CharField(blank=True, max_length=100, null=True)),
                ('p30_3', models.CharField(blank=True, max_length=100, null=True)),
                ('p30_4', models.CharField(blank=True, max_length=100, null=True)),
                ('p30_5', models.CharField(blank=True, max_length=100, null=True)),
                ('p30_6', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
