# Generated by Django 4.1.3 on 2022-12-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0025_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='t_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='t_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='t_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='t_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='t_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='t_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
